#!/usr/bin/env bash

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/util"

exists "${MI5_INIT}" && del "${MI5_INIT}"















	# return 0
# else



	#
  #   ! dir_ok "$ANDROID_ROOT" && creater_dir
  #   ! dir_ok "$ANDROID_ROOT_REPO" &&	cd "$ANDROID_ROOT" && repo init -u "$CYANOGEN_REPO" -b "$CYANOGEN_BRANCH" --depth=1
  #   ! file_ok "$ROOMSERVICE" && git clone "$ROOMSERVICE_REPO" "$LOCAL_MANIFESTS"
  #   different "$MI5_ROOT_MANIFEST" "$MI5_LOCAL_MANIFEST" && cp "$MI5_ROOT_MANIFEST" "$MI5_LOCAL_MANIFEST"
	#
  #   ! dir_ok "$ANDROID_CCACHE_DIR" && creater_dir "$ANDROID_CCACHE_DIR"
  #   ! file_ok "${ANDROID_CCACHE_DIR}/CACHEDIR.TAG" &&  CCACHE_DIR="${ANDROID_CCACHE_DIR}" ccache -M "${ANDROID_CCACHE_SIZE}"
	#
  #   touch "$MI5_ROOT/.init"
  # fi
	#
  # if [ ! -f "$MI5_ROOT/.init" ]; then
  #   return 1
  # else
  #   return 0
  # fi

	# init()
	# {

  # ÷"$ANDROID_ROOT" && check || fail
  # [ -f "$MI5_ROOT/.init" ] && { return 0 } || {
  #
	# [ ! -f "$MI5_ROOT/.init" ] &&
	# {
	# 	dir_ok "$ANDROID_ROOT" || creater_dir "$ANDROID_ROOT" && check || fail
  #
  #
	# 	dir_ok "$ANDROID_CCACHE_DIR" || creater_dir "$ANDROID_CCACHE_DIR"
	# 	dir_ok "$ANDROID_ROOT_REPO" ||	cd "$ANDROID_ROOT" && repo init -u "$CYANOGEN_REPO" -b "$CYANOGEN_BRANCH" --depth=1
	# 	dir_ok "$LOCAL_MANIFESTS" ||	creater_dir "$LOCAL_MANIFESTS"
	# 	file_ok "$ROOMSERVICE" || git clone "$ROOMSERVICE_REPO" "$LOCAL_MANIFESTS"
  # 	file_ok "${ANDROID_CCACHE_DIR}/CACHEDIR.TAG" || CCACHE_DIR="${ANDROID_CCACHE_DIR}" ccache -M "${ANDROID_CCACHE_SIZE}"
	# 	touch "$MI5_ROOT/.init"
	# 	return 0
	# } || {
	# 	update
	# }
# }
