#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"

# While $SOURCE is a symlink, resolve it
while [ -h "$SOURCE" ]; do
		 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		 SOURCE="$( readlink "$SOURCE" )"
		 # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
		 [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

MI5_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
MI5_LIB="${MI5_ROOT}/lib"
MI5_LIBS=(${MI5_LIB}/*)

for lib in "${MI5_LIBS[@]}"
do
	source "${lib}"
done

init_dirs

[ $# -eq 0 ] && print_help && exit 1;

while [ $# -gt 0 ]
do
	case "$1" in
		clean)	clean;;
		make)	make "$@"; shift;;
		mod)	mod;;
		sync)	sync;;
		flash) flash "$@"; shift;;
		unmod)	unmod;;
		purge)	purge;;
		splash)	splash;;
		rom)	rom;;
		*)
			echo >&2 \
			"usage: $0 [command]"
			exit 1;;
	esac
	shift
done

exit 0
#
