#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"

# While $SOURCE is a symlink, resolve it
while [ -h "$SOURCE" ]; do
		 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		 SOURCE="$( readlink "$SOURCE" )"
		 # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
		 [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

MI5_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
MI5_LIB="${MI5_ROOT}/lib"
MI5_LIBS=(${MI5_LIB}/*)

for lib in "${MI5_LIBS[@]}"
do
	source "${lib}"
done

clean
# env
# lib
make
mod
sync
unmod







#
