#!/usr/bin/env bash

export CELLS_GIT='https://github.com/n76/lacells-creator.git'
export CELLS_BIN='lacells-creator'
export CELLS_CFG='creator.cfg'

cells()
{
	! d_exists "${CELLS_DIR}" && mkd "${CELLS_DIR}"
	! d_exists "${CELLS_DIR}/.git" && git clone "${CELLS_GIT}" "${CELLS_DIR}"

	

  # get_miui_rom
  # get_miui_fastboot
}







# get_miui_rom()
# {
#   exists "${ROM_DIR}/.miuirom" && return 0
#   cd "${ROM_DIR}"
#   wget "${MIUI_BASE}/${MIUI_VER}/${MIUI_ROM}" -c --show-progress -P "${ROM_DIR}"
#   unzip "${MIUI_ROM}" -d "miui-rom" && touch "${ROM_DIR}/.miuirom"
# }
#
# get_miui_fastboot()
# {
#   exists "${ROM_DIR}/.miuifastboot" && return 0
#   cd "${ROM_DIR}"
#   wget "${MIUI_BASE}/${MIUI_VER}/${MIUI_FASTBOOT}" -c --show-progress -P "${ROM_DIR}"
#   tar xvf "${MIUI_FASTBOOT}" && mv -v "gemini_global_images_6.8.18_20160805.0000.29_6.0_global" "miui-fastboot" && touch "${ROM_DIR}/.miuifastboot"
# }
