#!/usr/bin/env bash

export CELLS_GIT='https://github.com/n76/lacells-creator.git'
export CELLS_BIN='lacells-creator'
export CELLS_CFG='creator.cfg'

cells_init()
{

	! d_exists "${CELLS_DIR}" && mkd "${CELLS_DIR}"
	! d_exists "${CELLS_DIR}/.git" && git clone "${CELLS_GIT}" "${CELLS_DIR}"
	! d_exists "${SDCARD}/.db" && mkd "${SDCARD}/.db"

}

cells_download()
{

	f_exists "${CELLS_DIR}/date" && export CELLS_DATE="$(source ${CELLS_DIR}/date)"

	if [ ! "${CELLS_DATE}" -eq "$(date '+%d')" ]; then
		secret && API_KEY="${API_KEY}" ./"${CELLS_BIN}" -d && date "+%d" > "${CELLS_DIR}/date"
	fi

}

cells()
{

	cells_init

	f_exists "${CELLS_DIR}/lacells.db" && rm -v "${CELLS_DIR}/lacells.db"

	cd "${CELLS_DIR}"
	# secret && echo $API_KEY $MCC
	# secret && API_KEY="${API_KEY}" ./"${CELLS_BIN}" -d -i -m -c"${MCC}" && date "+%d" > "${CELLS_DIR}/date"
	f_exists "${CELLS_DIR}/lacells.db" && cp -v "${CELLS_DIR}/lacells.db" "${SDCARD}/.db/lacells.db"
	cd "${MI5_ROOOT}"

}
