#!/usr/bin/env bash

export RECOVERY_IMG="${IMG_DIR}/twrp-recovery.img"

check_dev()
{
	fastboot getvar product 2>&1 | grep "^product: *MSM8996$"
	if [ $? -ne 0 ] ; then
		echo "Missmatching image and device";
		exit 1;
	else
		return 0
	fi
}

flash_splash()
{
	splash
	fastboot flash splash "${SPLASH_IMG}"
	if [ $? -ne 0 ] ; then echo "Flash splash error"; exit 1; fi
}

flash_recovery()
{
	fastboot flash recovery "${RECOVERY_IMG}"
	if [ $? -ne 0 ] ; then echo "Flash recovery error"; exit 1; fi
}

flash_original()
{
	get_miui_fastboot
	exists "${ROM_DIR}/miui-fastboot" && cd "${ROM_DIR}/miui-fastboot"
	exists "flash_all.sh" && echo sh flash_all.sh
}

_flash()
{
	if [ $# -eq 2 ]; then
		fastboot flash "${1}" "${2}"
	fi
}

flash_radio()
{
	get_miui_rom

	exists "${ROM_DIR}/miui-rom/firmware-update" && cd "${ROM_DIR}/miui-rom/firmware-update" || exit 1;

	_flash "cmnlib64" "cmnlib64.mbn"
	_flash "cmnlib" "cmnlib.mbn"
	_flash "hyp" "hyp.mbn"
	_flash "pmic" "pmic.elf"
	_flash "tz" "tz.mbn"
	_flash "aboot" "emmc_appsboot.mbn"
	_flash "devcfg" "devcfg.mbn"
	_flash "keymaster" "keymaster.mbn"
	_flash "xbl" "xbl.elf"
	_flash "rpm" "rpm.mbn"
	_flash "modem" "NON-HLOS.bin"
	_flash "logo" "logo.img"
	_flash "dsp" "adspso.bin"
	_flash "bluetooth" "BTFM.bin"

	_flash "cmnlib64bak" "cmnlib64.mbn"
	_flash "cmnlibbak" "cmnlib.mbn"
	_flash "hypbak" "hyp.mbn"
	_flash "pmicbak" "pmic.elf"
	_flash "tzbak" "tz.mbn"
	_flash "abootbak" "emmc_appsboot.mbn"
	_flash "devcfgbak" "devcfg.mbn"
	_flash "keymasterbak" "keymaster.mbn"
	_flash "xblbak" "xbl.elf"
	_flash "rpmbak" "rpm.mbn"

	flash_splash

	cd ${MI5_ROOT}
}

flash()
{
	cd "${MI5_ROOT}"

	check_dev

	if [ $# -eq 2 ]; then
		case "$2" in
			splash) flash_splash;;
			recovery)	flash_recovery;;
			radio)	flash_radio;;
			original) flash_original;;
			*)
				echo >&2 \
				"unknown flash target: $2"
				exit 1;;
		esac
	fi

}
