#!/usr/bin/env bash

export RECOVERY_IMG="${IMG_DIR}/twrp-recovery.img"

check_dev()
{
	fastboot getvar product 2>&1 | grep "^product: *MSM8996$"
	if [ $? -ne 0 ] ; then
		echo "Missmatching image and device";
		exit 1;
	else
		return 0
	fi
}

flash_splash()
{
	splash
	fastboot flash splash "${SPLASH_IMG}"
	if [ $? -ne 0 ] ; then echo "Flash splash error"; exit 1; fi
}

flash_recovery()
{
	fastboot flash recovery "${RECOVERY_IMG}"
	if [ $? -ne 0 ] ; then echo "Flash recovery error"; exit 1; fi
}

flash_original()
{
	get_miui_fastboot
	exists "${ROM_DIR}/miui-fastboot" && cd "${ROM_DIR}/miui-fastboot"
	exists "flash_all.sh" && echo sh flash_all.sh
}

flash_radio()
{
	get_miui_rom
	! exists "${ROM_DIR}/miui-rom" && exit 1;
	echo yeah
}

flash()
{
	cd "${MI5_ROOT}"

	check_dev

	if [ $# -eq 2 ]; then
		case "$2" in
			splash) flash_splash;;
			recovery)	flash_recovery;;
			radio)	flash_radio;;
			original) flash_original;;
			*)
				echo >&2 \
				"unknown flash target: $2"
				exit 1;;
		esac
	fi

}
