#!/usr/bin/env bash

purge()
{
  exists "${ANDROID_ROOT}" && rm -rfv "${ANDROID_ROOT}"
  exists "${ANDROID_CCACHE_DIR}" && rm -rfv "${ANDROID_CCACHE_DIR}"
  exists "${OUT_DIR}" && rm -rfv "${OUT_DIR}"
  exists "${ROM_DIR}" && rm -rfv "${ROM_DIR}"
  exists "${APK_DIR}" && rm -rfv "${APK_DIR}"
}
