#!/usr/bin/env bash

export MIUI_LATEST='http://bigota.d.miui.com/6.8.18/miui_MI5Global_6.8.18_4a1d3f0dfc_6.0.zip'
export MIUI_FASTBOOT='http://bigota.d.miui.com/6.8.18/gemini_global_images_6.8.18_20160805.0000.29_6.0_global_e3996a764f.tgz'

rom()
{
  
}
