#!/usr/bin/env bash

# 6.8.18 Global Dev
######################################
export MIUI_FASTBOOT='gemini_global_images_6.8.18_20160805.0000.29_6.0_global_e3996a764f.tgz'
export MIUI_ROM='miui_MI5Global_6.8.18_4a1d3f0dfc_6.0.zip'
export MIUI_ROM='miui_MI5Global_6.8.18_4a1d3f0dfc_6.0.zip'

# 6.8.23
######################################
export MIUI_ROM='http://bigota.d.miui.com/6.8.23/miui_MI5_6.8.23_47e61a6323_6.0.zip'

# 6.8.25
######################################
export MIUI_ROM='http://bigota.d.miui.com/6.8.25/miui_MI5Global_6.8.25_5a9ebd9518_6.0.zip'

# 6.9.1
######################################
export MIUI_ROM='http://bigota.d.miui.com/6.9.1/miui_MI5Global_6.9.1_fdacfd87fd_6.0.zip'
export MIUI_FASTBOOT='http://bigota.d.miui.com/6.9.1/gemini_global_images_6.9.1_20160805.0000.29_6.0_global_15c6339d4e.tgz'

# 6.9.8
######################################
export MIUI_ROM='http://bigota.d.miui.com/6.9.8/miui_MI5Global_6.9.8_d5849bd9c9_6.0.zip'
export MIUI_FASTBOOT='http://bigota.d.miui.com/6.9.8/gemini_global_images_6.9.8_20160805.0000.29_6.0_global_e0a37893b1.tgz'

# 6.9.22
######################################
export MIUI_ROM='http://bigota.d.miui.com/6.9.22/miui_MI5Global_6.9.22_f3dca81add_6.0.zip'
export MIUI_FASTBOOT='http://bigota.d.miui.com/6.9.22/gemini_global_images_6.9.22_20160805.0000.29_6.0_global_5f6a025591.tgz'

export MIUI_ROM='http://bigota.d.miui.com/6.10.20/miui_MI5Global_6.10.20_ae1c0aa2aa_6.0.zip'
export MIUI_FASTBOOT='http://bigota.d.miui.com/6.10.20/gemini_global_images_6.10.20_20160805.0000.29_6.0_global_c84d9fd6ba.tgz'


export DAT2IMG_UTIL="${MI5_ROOT}/util/sdat2img.py"
export UNPACKBOOTIMG_UTIL="${MI5_ROOT}/util/unpackbootimg"

export MIUI_ROM_DIR="${ROM_DIR}/miui-rom"
export MIUI_FASTBOOT_DIR="${ROM_DIR}/miui-fastboot"

get_miui_rom()
{
  exists "${ROM_DIR}/.miuirom" && return 0
  cd "${ROM_DIR}"
  wget "${MIUI_ROM}" -c --show-progress -P "${ROM_DIR}"
  unzip "${ROM_DIR}/$(basename ${MIUI_ROM})" -d "${MIUI_ROM_DIR}" && touch "${ROM_DIR}/.miuirom"
}

get_miui_fastboot()
{
  exists "${ROM_DIR}/.miuifastboot" && return 0
  cd "${ROM_DIR}"
  wget "${MIUI_BASE}/${MIUI_VER}/${MIUI_FASTBOOT}" -c --show-progress -P "${ROM_DIR}"
  tar xvf "${MIUI_FASTBOOT}" && mv -v "gemini_global_images_6.8.18_20160805.0000.29_6.0_global" "miui-fastboot" && touch "${ROM_DIR}/.miuifastboot"
}

convert_system_img()
{
  ! f_exists "${MIUI_ROM_DIR}/system.new.dat" && get_miui_rom
  ! f_exists "${MIUI_ROM_DIR}/system.img" && "${DAT2IMG_UTIL}" "${MIUI_ROM_DIR}/system.transfer.list" "${MIUI_ROM_DIR}/system.new.dat" "${MIUI_ROM_DIR}/system.img"
}

unpack_system()
{
  ! f_exists "${MIUI_ROM_DIR}/system.img" && convert_system_img
  f_exists "${MIUI_ROM_DIR}/system.done" && return 0
  ! d_exists "${MIUI_ROM_DIR}/system.d" && mkd "${MIUI_ROM_DIR}/system.d"
  ! d_exists "${MIUI_ROM_DIR}/system" && mkd "${MIUI_ROM_DIR}/system"
  ext4fuse "${MIUI_ROM_DIR}/system.img" "${MIUI_ROM_DIR}/system.d"
  rsync -rlptDvz "${MIUI_ROM_DIR}/system.d/" "${MIUI_ROM_DIR}/system"
  umount "${MIUI_ROM_DIR}/system.d"
  f_exists "${MIUI_ROM_DIR}/system/build.prop" && touch "${MIUI_ROM_DIR}/system.done"
}

unpack_boot()
{
  ! f_exists "${MIUI_ROM_DIR}/boot.img" && get_miui_rom
  f_exists "${MIUI_ROM_DIR}/boot.done" && return 0
  ! f_exists "${MIUI_ROM_DIR}/boot.img-zImage" && "${UNPACKBOOTIMG_UTIL}" -i "${MIUI_ROM_DIR}/boot.img" -o "${MIUI_ROM_DIR}"
  f_exists "${MIUI_ROM_DIR}/boot.img-zImage" && touch "${MIUI_ROM_DIR}/boot.done"
}

rom_clean_system()
{
  f_exists "${MIUI_ROM_DIR}/system.done" && rm -v "${MIUI_ROM_DIR}/system.done"
  f_exists "${MIUI_ROM_DIR}/system.img" && rm -v "${MIUI_ROM_DIR}/system.img"
  d_exists "${MIUI_ROM_DIR}/system.d" && rm -rfv "${MIUI_ROM_DIR}/system.d"
  d_exists "${MIUI_ROM_DIR}/system" && rm -rfv "${MIUI_ROM_DIR}/system"
}

rom_clean()
{
  d_exists "${MIUI_ROM_DIR}" && rm -rfv "${MIUI_ROM_DIR}"
  f_exists "${ROM_DIR}/.miuirom" && rm -v "${ROM_DIR}/.miuirom"
}

rom()
{

	if [ $# -eq 2 ]; then
		case "$2" in
			clean) rom_clean;;
			get)	get_miui_rom;;
			convert)	convert_system_img;;
			unpack) unpack_system; unpack_boot;;
			*)
				echo >&2 \
				"unknown flash target: $2"
				exit 1;;
		esac
	fi

  # unpack_system
  # get_miui_rom
  # convert_system_img
  #
  # # clean_system
  # unpack_system
}
