#!/usr/bin/env bash

sync()
{
	setup_env
	cd "${ANDROID_ROOT}" && repo sync -c -j8
}
# . "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/util"
#
# modded && unmod
# cd "${ANDROID_ROOT}" && repo sync -c -j8
# modded && mod
# cd "${MI5_ROOT}"
# #
# ! exists "${ANDROID_ROOT}/build/envsetup.sh" && sync
# echo sync
