#!/usr/bin/env bash

unmod()
{
  exists "${MODS_CONFIG}" && source "${MODS_CONFIG}"

  for backup in "${MODS_BACKUP[@]}"
  do
    if f_exists "${MODS_DIR}/$(basename $backup).bak"; then
      mv -v "${MODS_DIR}/$(basename ${backup}).bak" "${ANDROID_ROOT}/${backup}"
    fi
  done

  for mod in "${MODS[@]}"
  do
    out "--[${mod}]"
    if f_exists "${MODS_DIR}/${mod}/${mod}"; then
      . "${MODS_DIR}/${mod}/${mod}"
      "${mod}_disable"
    fi
  done
}
# . "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/util"
#
# out "Disable MODs"
# MODS=($(entries))
#
# for mod in "${MODS[@]}"
# do
#   if f_exists "${MODS_DIR}/${mod}/disable"; then
#     out "Restoring [$mod]."
#     . "${MODS_DIR}/${mod}/disable"
# 		out "MODDED=0" > "${MI5_INIT}"
#   fi
# done
# exists "${MODS_CONFIG}" && source "${MODS_CONFIG}"
#
