#!/usr/bin/env bash

unmod()
{
  exists "${MODS_CONFIG}" && source "${MODS_CONFIG}"
  for mod in "${MODS[@]}"
  do
    out "--[${mod}]"
    if f_exists "${MODS_DIR}/${mod}/${mod}"; then
      . "${MODS_DIR}/${mod}/${mod}"
      "${mod}_disable"
    fi
  done
}
# . "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/util"
#
# out "Disable MODs"
# MODS=($(entries))
#
# for mod in "${MODS[@]}"
# do
#   if f_exists "${MODS_DIR}/${mod}/disable"; then
#     out "Restoring [$mod]."
#     . "${MODS_DIR}/${mod}/disable"
# 		out "MODDED=0" > "${MI5_INIT}"
#   fi
# done
# exists "${MODS_CONFIG}" && source "${MODS_CONFIG}"
#
