#!/usr/bin/env bash

unmod()
{
  echo unmod
}
# . "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/util"
#
# out "Disable MODs"
# MODS=($(entries))
#
# for mod in "${MODS[@]}"
# do
#   if f_exists "${MODS_DIR}/${mod}/disable"; then
#     out "Restoring [$mod]."
#     . "${MODS_DIR}/${mod}/disable"
# 		out "MODDED=0" > "${MI5_INIT}"
#   fi
# done
